@echo off
echo Starting Synco App Services in separate windows...
cd /d "%~dp0"

echo Starting Prisma DB...
REM start cmd /k "cd backend && npx prisma dev"

echo Starting Express Backend...
start cmd /k "cd backend && npm run dev"

echo Starting NestJS Backend...
start cmd /k "cd backend-nest && npm run start:dev"

echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
